### PR TITLE
Add Pull Request template to repo

### PR DESCRIPTION
**Pull request by arwehrman**
- Adds a PR template to the Think Dev Standards repo

This pr closes [THINKDOCS-112](https://thinkcompany.atlassian.net/browse/THINKDOCS-112?atlOrigin=eyJpIjoiNzFkMWE2MjMzZTE3NGY1YTlhYjliMzI0MTA2YjE4NTQiLCJwIjoiaiJ9)

### CODE REVIEW

**Review by think-john — CHANGES_REQUESTED** [review]
I started thinking about what we actually want in here, and I couldn't resist making changes. HERE THEY ARE:

```
## Changes

- Summarize the changes made in this pull request

## Checklist
Check all the boxes that apply to this pull request

- [ ] This pull request requires an update to dependencies
- [ ] Accessibility tests have passed 
- [ ] Automated tests have passed
- [ ] This change looks good on mobile

## How To Review
Describe how the reviewer can see these changes, either by running the code locally on their own machine or viewing it in a published environment.

## Tickets Closed
List tickets closed by this pull request

- Closes [THINKDOCS-##](#link#)
```

**Comment by think-john** [comment]
I see that this puts the template at the _root_ of the repository, which works just fine for me!

I see that other options are to put it into `/docs/` or `/.github/`.  I like having it at the root, honestly.

**Comment by arwehrman** [comment]
I'm going to update the checklist since this code is mainly documentation code and some of the items on our checklist doesn't really apply

**Review by think-john — APPROVED** [review]

**Review by andyknapp — APPROVED** [review]
IMO it would be nice to have a section at the top indicating status of the PR - Complete, In Progress, Other(?). Otherwise, this looks great!

**Comment by brendanmckeown** [comment]
> I started thinking about what we actually want in here, and I couldn't resist making changes. HERE THEY ARE:
> 
> ```
> ## Changes
> 
> - Summarize the changes made in this pull request
> 
> ## Checklist
> Check all the boxes that apply to this pull request
> 
> - [ ] This pull request requires an update to dependencies
> - [ ] Accessibility tests have passed 
> - [ ] Automated tests have passed
> - [ ] This change looks good on mobile
> 
> ## How To Review
> Describe how the reviewer can see these changes, either by running the code locally on their own machine or viewing it in a published environment.
> 
> ## Tickets Closed
> List tickets closed by this pull request
> 
> - Closes [THINKDOCS-##](#link#)
> ```

I don't see any automated tests for this project – so I don't think it makes sense to add it as a checklist item until we do have some.

**Review by brendanmckeown — APPROVED** [review]

**Pull request merged**
