### PR TITLE
feat: add react development standards page

### PR DESCRIPTION
**Pull request by nishthinks**
What Changed:
- Added a section for React development standards
- Removed redundant titles from javascript sections

How to Test:
- Checkout this branch
- run npm start
- navigate to localhost:8000

### CODE REVIEW

**Comment by think-john** [comment]
I approved the Percy build to get rid of the "build failed" red error message.

Nish, since we're using Netlify for deploy previews, the "How to test" is even easier than the steps you listed.  In order to test, all the reviewer has to do is go to the deploy preview, chis is: https://deploy-preview-5--think-dev-standards.netlify.app/javascript/react-best-practices/ 
(You can find the deploy preview link by clicking "Details" next to the "Deploy Preview ready!" line in the "checks"

**Comment by think-john** [comment]
Nish, was the intent of this PR to add a _blank_ React Development Standards page (in which case, this seems just fine), or was it your intent to _also_ add some standards?

**Comment by nishthinks** [comment]
> I approved the Percy build to get rid of the "build failed" red error message.
> 
> Nish, since we're using Netlify for deploy previews, the "How to test" is even easier than the steps you listed. In order to test, all the reviewer has to do is go to the deploy preview, chis is: https://deploy-preview-5--think-dev-standards.netlify.app/javascript/react-best-practices/ (You can find the deploy preview link by clicking "Details" next to the "Deploy Preview ready!" line in the "checks"

That is awesome! Thanks for approving the build.

**Comment by nishthinks** [comment]
> Nish, was the intent of this PR to add a _blank_ React Development Standards page (in which case, this seems just fine), or was it your intent to _also_ add some standards?

Just wanted to open a draft PR for a WIP placeholder. I will be adding _some_ standards to the page before publishing the PR shortly!

**Comment by think-john** [comment]
> Just wanted to open a draft PR for a WIP placeholder. I will be adding _some_ standards to the page before publishing the PR shortly!

Oh, I see the "draft" status pill next to the PR now. Thank you! I'll ignore further updates until the "draft" bug goes away.

**Comment by think-john** [comment]
Say @nishthinks , because you have included me as a reviewer, Github likes to remind me daily that this PR is "three days stale."  That's not the case, of course, because it's still a draft.

What do you think about removing reviewers until this PR is out of "draft" status and you're actively soliciting feedback?

**Comment by nishthinks** [comment]
> Say @nishthinks , because you have included me as a reviewer, Github likes to remind me daily that this PR is "three days stale." That's not the case, of course, because it's still a draft.
> 
> What do you think about removing reviewers until this PR is out of "draft" status and you're actively soliciting feedback?

Yes, good idea @think-john! I wasn't anticipating that a draft PR will send out notifications. Removed the reviewers and will add them back once it's ready for review.

**Comment by think-john** [comment]
Say, @brendanmckeown and @bdolly , I think one of us three needs to resolve the conflicts, remove the "draft" label, and otherwise carry this PR across the finish line.  I, uh... I don't see any reason why it shouldn't be ME, so I'm going to do it!

**Comment by think-john** [comment]
I have fixed up this PR by rebasing on to `main` and fixing conflicts. Then I amended a typo and redid the numbering on the sections in the javascript section.  As long as Percy and Netlify like this, I _thiiiiink_ this is now ready for regular review.

**Review by think-john — APPROVED** [review]
APPROVIN' MY OWN PRRRRRRR

**Comment by think-john** [comment]
@bdolly or @brendanmckeown , who will be first to approve my PR?  The next approver unlocks the merge! Oh boy!

**Comment by brendanmckeown** [comment]
I am going to pull the latest content from the React best practices Confluence page from Ascensus and add to this PR.

**Review by brendanmckeown — APPROVED** [review]

**Pull request merged**
