### PR TITLE
THINKDOCS-79 remove jQuery section

### PR DESCRIPTION
**Pull request by arwehrman**
This PR does the following:

- moves jQuery section from dev standards into Confluence => [Guidelines and Best Practices](https://thinkcompany.atlassian.net/wiki/spaces/DEV/pages/3230990353/jQuery) 
- removes reference links for jQuery
- adds blurb about jQuery in the Javascript section
- removes empty Large Application section

closes: [THINKDOCS-79](https://thinkcompany.atlassian.net/browse/THINKDOCS-79?atlOrigin=eyJpIjoiNjRlYjYwZTUzYzMzNGVmNmE4MzNmZDYzODM2Y2EzOTkiLCJwIjoiaiJ9)

### CODE REVIEW

**Review by think-john — APPROVED** [review]
I love the use of present-tense imperative on all four commits, and I love the changes to the copy.  I like that we say "Yes, jQuery exists" but we have gotten rid of lots of space-taking-up documentation about it.

Attempting to find something to nitpick about.... nope! Can't think of anything. Thank you!

**Review by andyknapp — COMMENTED** [review]
Looks great!

**Review by rayng86 — APPROVED** [review]
the changes here looks good to me.

one thing I wanted to mention that wasn't part of the changes you made here but does show up currently in production is the double posting of the resources header. Just wanted to point that out incase you want to correct that.

https://raw.githubusercontent.com/thinkcompany/think_dev-standards/5cf2bc39936de995ee5cf3e45cb68193aa2ab598/content/javascript/resources/index.md

image

which results in:
image

**Review by andyknapp — APPROVED** [review]

**Comment by arwehrman** [comment]
Thanks @rayng86  for the Resources head up.
I'm going to put note in the Update resources section issue to make this change.

**Pull request merged**
